# Site settings
title: pgsql.site на русском языке

description: Собираем материалы по развертыванию приложений с помощью самых современных инструментова автоматизации

keywords: PGSQL, DevOps, SRE, Clouds, Linux, Docker, Kubernetes, Git, FluxCD, ArgoCD

baseurl: '' # the subpath of your site, e.g. /blog/
url: 'https://pgsql.site' # the base hostname & protocol for your site

# Build settings
markdown: kramdown

plugins:
  - jekyll-sitemap
