# Site settings
title: pgsql

description: Информация об отечественном дистрибутиве базы банных на основе PostgreSQL от DiaSoft

keywords: Отечественный дистрибутив PostgreSQL, Лицензии.ру, Diasoft, База для замены Oracle, MSSQL

baseurl: '' # the subpath of your site, e.g. /blog/
url: 'https://pgsql.site' # the base hostname & protocol for your site

# Build settings
markdown: kramdown

plugins:
  - jekyll-sitemap
