# Site settings
title: pgsql

description: Информация об отечественном дистрибутиве базы банных на основе PostgreSQL от DiaSoft

keywords: PGSQL, PostgreSQL, DataBase, Diasoft, Q.Digital

baseurl: '' # the subpath of your site, e.g. /blog/
url: 'https://pgsql.site' # the base hostname & protocol for your site

# Build settings
markdown: kramdown

plugins:
  - jekyll-sitemap
